name: Manual Cycle Bot - Single Account

on:
  workflow_dispatch:

concurrency:
  group: wolf-cycle-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Start Cycle Bot
        env:
          U_MAIL: ${{ secrets.U_MAIL }}
          U_PASS: ${{ secrets.U_PASS }}
        run: |
          echo "🚀 بدء تشغيل البوت لحساب واحد"
          node app.js
